### PR TITLE
Fix donut chart not updating for a new dataset

### PR DESCRIPTION
**Pull request by karmi**
1/ Keep the color based on object constancy
2/ Remove arcs which are not present in the data anymore on `exit()`

Tested manually.

### CODE REVIEW

**Comment by egaumer** [comment]
Cool, thanks. Hadn't noticed this because I had been using all_terms:true

**Comment by karmi** [comment]
I friend of mine has bumped into this, when he used the donut chart for interaction. I think it should also help when you load the same facet for different data (query, filter, etc), but haven't tested it.

**Comment by egaumer** [comment]
And here I thought you might be trying out AngularJS :)

**Comment by karmi** [comment]
Indirectly, Eric, indirectly... :)

**Comment by stevemartingale** [comment]
Hey thanks for the fix but I noticed that is not consistently applied in the repository.  That is, it is in not in any of the donut code in the dist folder.

**Pull request merged**
